### ISSUE TITLE
^clearprogress -> "difficulty is not defined"

### ISSUE THREAD

**Issue by scarfur** [ericbright2002/Forged_in_Obsidian#4]
`var difficulty = "";` or `var difficulty = "Epic";` for example at line 311 in [starforged_progress.sfile](https://github.com/ericbright2002/Forged_in_Obsidian/blob/main/Support/inlineScripts/starforged_progress.sfile.md) fixes the issue

✌🏽

**Comment by ericbright2002** [comment]
Fixed!  Thank you!
